server:
   port: 8086
spring:
  application:
    name: pupilservice
  mvc:
    servlet:
      load-on-startup: 1  
  profiles:
    active:
      default
  zipkin:
    baseUrl: http://localhost:9411      
  cloud:
    config:
      enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/